#!/usr/bin/env python3
"""Bundle Wish_Acknowledgement.VR into ONE self-contained .html file.

Why: a single file can be shared over WhatsApp / AirDrop / email and opened
straight from the file system with no hosting at all. The normal multi-file
version stays the primary build for GitHub Pages.

Usage:  python3 tools/build-standalone.py
Output: Wish_Acknowledgement.VR.single-file.html  (project root)
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "index.html"
TARGET = ROOT / "Wish_Acknowledgement.VR.single-file.html"

html = SOURCE.read_text(encoding="utf-8")

# 1 · inline the stylesheet
css_path = ROOT / "assets/css/style.css"
css = css_path.read_text(encoding="utf-8")
html = html.replace(
    '<link rel="stylesheet" href="assets/css/style.css" />',
    f"<style>\n/* inlined from assets/css/style.css */\n{css}\n</style>",
)

# 2 · inline the scripts, in the order they are declared
def inline_script(match: "re.Match[str]") -> str:
    rel = match.group(1)
    code = (ROOT / rel).read_text(encoding="utf-8")
    return f"<script>\n/* inlined from {rel} */\n{code}\n</script>"


html = re.sub(r'<script src="(assets/js/[^"]+)" defer></script>', inline_script, html)

# 3 · drop the tags that point at files a lone .html cannot carry with it
#     (crawlers never see a file:// page, so the share assets are unnecessary)
for pattern in (
    r'\n<link rel="manifest"[^>]*>',
    r'\n<link rel="apple-touch-icon"[^>]*>',
    r'\n<meta property="og:image"[^>]*>',
    r'\n<meta property="og:image:[^>]*>',
    r'\n<meta name="twitter:image"[^>]*>',
):
    html = re.sub(pattern, "", html)

banner = (
    "<!--\n"
    "  Wish_Acknowledgement.VR — single-file build (CSS + JS inlined).\n"
    "  Generated by tools/build-standalone.py — edit the files in assets/, not this file.\n"
    "  Send it to a friend, or open it directly: index.html?name=TheirName\n"
    "-->\n"
)
html = html.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + banner, 1)

TARGET.write_text(html, encoding="utf-8")
print(f"✔ wrote {TARGET.relative_to(ROOT)}  ({TARGET.stat().st_size / 1024:.1f} KB)")
